import { BrushPresetId, BrushSettings, ColorPalette } from '../types';

export const BRUSH_PRESETS: Record<BrushPresetId, BrushSettings> = {
  pencil_standard: {
    id: 'pencil_standard',
    name: 'قلم رصاص',
    category: 'رصاص وتخطيط',
    description: 'قلم رصاص طبيعي للرسم التمهيدي والتظليل الناعم',
    size: 6,
    opacity: 0.85,
    flow: 0.8,
    hardness: 0.6,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.5,
  },
  pencil_hb: {
    id: 'pencil_hb',
    name: 'قلم رصاص HB',
    category: 'رصاص وتخطيط',
    description: 'قلم رصاص كلاسيكي متوسط الصلابة بخطوط متوازنة',
    size: 4,
    opacity: 0.9,
    flow: 0.85,
    hardness: 0.75,
    spacing: 0.08,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.0,
  },
  pencil_mech: {
    id: 'pencil_mech',
    name: 'قلم رصاص ميكانيكي',
    category: 'رصاص وتخطيط',
    description: 'سن رفيع دقيق 0.5 ملم للرسم الهندسي والتفاصيل الدقيقة',
    size: 2,
    opacity: 0.95,
    flow: 0.9,
    hardness: 0.9,
    spacing: 0.05,
    smoothing: 0.25,
    pressureSize: false,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  ink_pen: {
    id: 'ink_pen',
    name: 'قلم حبر',
    category: 'أحبار وخطوط',
    description: 'قلم حبر سائل انسيابي مع استجابة ممتازة لحساسية الضغط',
    size: 8,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.9,
    spacing: 0.05,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  fine_liner: {
    id: 'fine_liner',
    name: 'قلم حبر دقيق',
    category: 'أحبار وخطوط',
    description: 'قلم تحديد تقني ثابت العرض للخطوط الهندسية والمانجا',
    size: 3,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.04,
    smoothing: 0.6,
    pressureSize: false,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  highlighter: {
    id: 'highlighter',
    name: 'قلم تحديد',
    category: 'أحبار وخطوط',
    description: 'قلم فسفوري مشطوف شبه شفاف للتظليل والإبراز',
    size: 24,
    opacity: 0.45,
    flow: 0.7,
    hardness: 0.9,
    spacing: 0.1,
    smoothing: 0.3,
    pressureSize: false,
    pressureOpacity: false,
    angle: 45,
    scatter: 0,
  },
  calligraphy: {
    id: 'calligraphy',
    name: 'قلم خط عربي',
    category: 'أحبار وخطوط',
    description: 'قصبة خط عربي مشطوفة بزاوية 45 درجة لتنفيذ خط الرقعة والنسخ والديواني',
    size: 18,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.05,
    smoothing: 0.7,
    pressureSize: true,
    pressureOpacity: false,
    angle: 45,
    scatter: 0,
  },
  brush_pen: {
    id: 'brush_pen',
    name: 'قلم فرشاة',
    category: 'أحبار وخطوط',
    description: 'قلم تحبير ياباني مرن يتغير سمكه بسلاسة متناهية مع قوة الضغط',
    size: 14,
    opacity: 1.0,
    flow: 0.95,
    hardness: 0.8,
    spacing: 0.06,
    smoothing: 0.55,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  marker: {
    id: 'marker',
    name: 'قلم ماركر',
    category: 'أحبار وخطوط',
    description: 'ماركر كحولية عريضة برأس لباد للتلوين والتصاميم السريعة',
    size: 20,
    opacity: 0.8,
    flow: 0.85,
    hardness: 0.85,
    spacing: 0.08,
    smoothing: 0.4,
    pressureSize: false,
    pressureOpacity: true,
    angle: 30,
    scatter: 0,
  },
  soft_brush: {
    id: 'soft_brush',
    name: 'فرشاة ناعمة',
    category: 'فراشي تلوين',
    description: 'فرشاة تلوين بتدرج ناعم جداً للتظليل والدمج اللوني المتدرج',
    size: 32,
    opacity: 0.7,
    flow: 0.5,
    hardness: 0.1,
    spacing: 0.12,
    smoothing: 0.45,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  hard_brush: {
    id: 'hard_brush',
    name: 'فرشاة صلبة',
    category: 'فراشي تلوين',
    description: 'فرشاة أساسية بحواف حادة لملء المساحات والرسم الرقمي المحدد',
    size: 16,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.95,
    spacing: 0.05,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  airbrush: {
    id: 'airbrush',
    name: 'فرشاة هوائية',
    category: 'فراشي تلوين',
    description: 'بخاخ هوائي فائق النعومة لرسم تأثيرات الضوء والتوهج والظلال',
    size: 45,
    opacity: 0.5,
    flow: 0.35,
    hardness: 0.0,
    spacing: 0.15,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 4,
  },
  watercolor: {
    id: 'watercolor',
    name: 'فرشاة ألوان مائية',
    category: 'فراشي تلوين',
    description: 'تأثير الألوان المائية الشفافة الرطبة مع امتزاج الطبقات المجاورة',
    size: 28,
    opacity: 0.6,
    flow: 0.55,
    hardness: 0.3,
    spacing: 0.1,
    smoothing: 0.6,
    pressureSize: true,
    pressureOpacity: true,
    angle: 15,
    scatter: 2,
  },
  oil_brush: {
    id: 'oil_brush',
    name: 'فرشاة زيتية',
    category: 'فراشي تلوين',
    description: 'فرشاة زيتية سميكة بملامس شعر الفرشاة الطبيعية على القماش',
    size: 22,
    opacity: 0.95,
    flow: 0.9,
    hardness: 0.7,
    spacing: 0.08,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: true,
    angle: 60,
    scatter: 1.5,
  },
  acrylic: {
    id: 'acrylic',
    name: 'فرشاة أكريليك',
    category: 'فراشي تلوين',
    description: 'ألوان أكريليك سريعة الجفاف بتغطية قوية وخطوط واضحة المعالم',
    size: 18,
    opacity: 0.95,
    flow: 0.95,
    hardness: 0.8,
    spacing: 0.06,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  charcoal: {
    id: 'charcoal',
    name: 'فحم',
    category: 'فحم وباستيل',
    description: 'فحم طبيعي غني ذو ملمس حبيبي خشن للتخطيط والتظليل الدرامي',
    size: 24,
    opacity: 0.85,
    flow: 0.75,
    hardness: 0.5,
    spacing: 0.12,
    smoothing: 0.3,
    pressureSize: true,
    pressureOpacity: true,
    angle: 45,
    scatter: 5,
  },
  chalk: {
    id: 'chalk',
    name: 'طباشير',
    category: 'فحم وباستيل',
    description: 'طباشير جاف ببودرة ناعمة وملمس متفتت كلاسيكي',
    size: 20,
    opacity: 0.8,
    flow: 0.7,
    hardness: 0.6,
    spacing: 0.14,
    smoothing: 0.25,
    pressureSize: true,
    pressureOpacity: true,
    angle: 30,
    scatter: 6,
  },
  pastel: {
    id: 'pastel',
    name: 'باستيل',
    category: 'فحم وباستيل',
    description: 'باستيل ناعم مخملي يندمج بسهولة لإنشاء تدرجات لونية ساحرة',
    size: 26,
    opacity: 0.8,
    flow: 0.7,
    hardness: 0.4,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 20,
    scatter: 4,
  },
  crayon: {
    id: 'crayon',
    name: 'ألوان شمعية',
    category: 'فحم وباستيل',
    description: 'ألوان شمع شمعية ذات ملمس غير متجانس يحاكي الرسم اليدوي',
    size: 16,
    opacity: 0.9,
    flow: 0.85,
    hardness: 0.7,
    spacing: 0.12,
    smoothing: 0.2,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 3.5,
  },
  spray: {
    id: 'spray',
    name: 'بخاخ',
    category: 'تأثيرات وبكسل',
    description: 'علبة رذاذ وبخاخ غرافيتي بنقاط متناثرة متباعدة',
    size: 38,
    opacity: 0.7,
    flow: 0.6,
    hardness: 0.1,
    spacing: 0.2,
    smoothing: 0.2,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 18,
  },
  textured: {
    id: 'textured',
    name: 'فرشاة نسيجية',
    category: 'تأثيرات وبكسل',
    description: 'فرشاة بنمط قماش كانفاس متقاطع لإضفاء عمق فني للأعمال',
    size: 30,
    opacity: 0.85,
    flow: 0.8,
    hardness: 0.6,
    spacing: 0.1,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 8,
  },
  smudge: {
    id: 'smudge',
    name: 'فرشاة دمج',
    category: 'تأثيرات وبكسل',
    description: 'أداة دمج سائل تمزج الألوان المرسومة مثل طرف الإصبع',
    size: 25,
    opacity: 0.7,
    flow: 0.7,
    hardness: 0.3,
    spacing: 0.08,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  blur: {
    id: 'blur',
    name: 'فرشاة تمويه',
    category: 'تأثيرات وبكسل',
    description: 'تنعيم وتمويه الحواف الصامتة لإنشاء عمق ميداني هادئ',
    size: 28,
    opacity: 0.65,
    flow: 0.6,
    hardness: 0.2,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  pixel: {
    id: 'pixel',
    name: 'فرشاة بكسل',
    category: 'تأثيرات وبكسل',
    description: 'فرشاة رسم البكسل آرت (Pixel Art) بحواف حادة بدون تنعيم نهائياً',
    size: 4,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.01,
    smoothing: 0.0,
    pressureSize: false,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  eraser: {
    id: 'eraser',
    name: 'ممحاة ناعمة / صلبة',
    category: 'رصاص وتخطيط',
    description: 'ممحاة لمسح الخطوط والألوان بشفافية أو حدة حسب الإعدادات',
    size: 22,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.8,
    spacing: 0.08,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
};

export const PRESET_COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'essential',
    name: 'الألوان الأساسية',
    colors: [
      '#000000', '#ffffff', '#e63946', '#f1faee', '#a8dadc', '#457b9d', '#1d3557',
      '#f77f00', '#fcbf49', '#eae2b7', '#2a9d8f', '#264653', '#e76f51', '#9b5de5'
    ]
  },
  {
    id: 'nature',
    name: 'ألوان الطبيعة',
    colors: [
      '#2d6a4f', '#40916c', '#52b788', '#74c69d', '#95d5b2', '#b7e4c7', '#d8f3dc',
      '#606c38', '#283618', '#dda15e', '#bc6c25', '#8c1c13', '#bf4342', '#e7c169'
    ]
  },
  {
    id: 'skin_tones',
    name: 'درجات البشرة',
    colors: [
      '#2d1b00', '#4a2c00', '#6f441b', '#8d5524', '#c68642', '#e0ac69', '#f1c27d',
      '#ffdbac', '#fae1c5', '#fce8d5', '#e8b4b8', '#d48b94', '#9e5a63', '#4a252b'
    ]
  },
  {
    id: 'pastel',
    name: 'ألوان الباستيل',
    colors: [
      '#ffb3ba', '#ffdfba', '#ffffba', '#baffc9', '#bae1ff', '#e8dff5', '#fce1e4',
      '#fcf4dd', '#ddedea', '#daeaf6', '#fedcd2', '#dfccf1', '#f6eac2', '#c1e7e3'
    ]
  },
  {
    id: 'grayscale',
    name: 'تدرجات الرمادي',
    colors: [
      '#000000', '#171717', '#262626', '#404040', '#525252', '#737373', '#a3a3a3',
      '#d4d4d4', '#e5e5e5', '#f5f5f5', '#fafafa', '#ffffff', '#334155', '#64748b'
    ]
  },
  {
    id: 'cyberpunk_neon',
    name: 'ألوان النيون',
    colors: [
      '#00f0ff', '#ff003c', '#ffe600', '#05d9e8', '#ff2a6d', '#01012b', '#d1f7ff',
      '#00ff66', '#ff00ff', '#7928ca', '#39ff14', '#ff073a', '#00e5ff', '#ffb800'
    ]
  }
];
