import { BrushPresetId, BrushSettings, ColorPalette } from '../types';

export const BRUSH_PRESETS: Record<BrushPresetId, BrushSettings> = {
  pencil_standard: {
    id: 'pencil_standard',
    name: 'قلم رصاص',
    category: 'رصاص وتخطيط',
    description: 'قلم رصاص طبيعي للرسم التمهيدي والتظليل الناعم',
    size: 6,
    opacity: 0.85,
    flow: 0.8,
    hardness: 0.6,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.5,
  },
  pencil_hb: {
    id: 'pencil_hb',
    name: 'قلم رصاص HB',
    category: 'رصاص وتخطيط',
    description: 'قلم رصاص كلاسيكي متوسط الصلابة بخطوط متوازنة',
    size: 4,
    opacity: 0.9,
    flow: 0.85,
    hardness: 0.75,
    spacing: 0.08,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.0,
  },
  pencil_mech: {
    id: 'pencil_mech',
    name: 'قلم رصاص ميكانيكي',
    category: 'رصاص وتخطيط',
    description: 'سن رفيع دقيق 0.5 ملم للرسم الهندسي والتفاصيل الدقيقة',
    size: 2,
    opacity: 0.95,
    flow: 0.9,
    hardness: 0.9,
    spacing: 0.05,
    smoothing: 0.25,
    pressureSize: false,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  ink_pen: {
    id: 'ink_pen',
    name: 'قلم حبر',
    category: 'أحبار وخطوط',
    description: 'قلم حبر سائل انسيابي مع استجابة ممتازة لحساسية الضغط',
    size: 8,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.9,
    spacing: 0.05,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  fine_liner: {
    id: 'fine_liner',
    name: 'قلم حبر دقيق',
    category: 'أحبار وخطوط',
    description: 'قلم تحديد تقني ثابت العرض للخطوط الهندسية والمانجا',
    size: 3,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.04,
    smoothing: 0.6,
    pressureSize: false,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  highlighter: {
    id: 'highlighter',
    name: 'قلم تحديد',
    category: 'أحبار وخطوط',
    description: 'قلم فسفوري مشطوف شبه شفاف للتظليل والإبراز',
    size: 24,
    opacity: 0.45,
    flow: 0.7,
    hardness: 0.9,
    spacing: 0.1,
    smoothing: 0.3,
    pressureSize: false,
    pressureOpacity: false,
    angle: 45,
    scatter: 0,
  },
  calligraphy: {
    id: 'calligraphy',
    name: 'قلم خط عربي',
    category: 'أحبار وخطوط',
    description: 'قصبة خط عربي مشطوفة بزاوية 45 درجة لتنفيذ خط الرقعة والنسخ والديواني',
    size: 18,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.05,
    smoothing: 0.7,
    pressureSize: true,
    pressureOpacity: false,
    angle: 45,
    scatter: 0,
  },
  brush_pen: {
    id: 'brush_pen',
    name: 'قلم فرشاة',
    category: 'أحبار وخطوط',
    description: 'قلم تحبير ياباني مرن يتغير سمكه بسلاسة متناهية مع قوة الضغط',
    size: 14,
    opacity: 1.0,
    flow: 0.95,
    hardness: 0.8,
    spacing: 0.06,
    smoothing: 0.55,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  marker: {
    id: 'marker',
    name: 'قلم ماركر',
    category: 'أحبار وخطوط',
    description: 'ماركر كحولية عريضة برأس لباد للتلوين والتصاميم السريعة',
    size: 20,
    opacity: 0.8,
    flow: 0.85,
    hardness: 0.85,
    spacing: 0.08,
    smoothing: 0.4,
    pressureSize: false,
    pressureOpacity: true,
    angle: 30,
    scatter: 0,
  },
  soft_brush: {
    id: 'soft_brush',
    name: 'فرشاة ناعمة',
    category: 'فراشي تلوين',
    description: 'فرشاة تلوين بتدرج ناعم جداً للتظليل والدمج اللوني المتدرج',
    size: 32,
    opacity: 0.7,
    flow: 0.5,
    hardness: 0.1,
    spacing: 0.12,
    smoothing: 0.45,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  hard_brush: {
    id: 'hard_brush',
    name: 'فرشاة صلبة',
    category: 'فراشي تلوين',
    description: 'فرشاة أساسية بحواف حادة لملء المساحات والرسم الرقمي المحدد',
    size: 16,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.95,
    spacing: 0.05,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  airbrush: {
    id: 'airbrush',
    name: 'فرشاة هوائية',
    category: 'فراشي تلوين',
    description: 'بخاخ هوائي فائق النعومة لرسم تأثيرات الضوء والتوهج والظلال',
    size: 45,
    opacity: 0.5,
    flow: 0.35,
    hardness: 0.0,
    spacing: 0.15,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 4,
  },
  watercolor: {
    id: 'watercolor',
    name: 'فرشاة ألوان مائية',
    category: 'فراشي تلوين',
    description: 'تأثير الألوان المائية الشفافة الرطبة مع امتزاج الطبقات المجاورة',
    size: 28,
    opacity: 0.6,
    flow: 0.55,
    hardness: 0.3,
    spacing: 0.1,
    smoothing: 0.6,
    pressureSize: true,
    pressureOpacity: true,
    angle: 15,
    scatter: 2,
  },
  oil_brush: {
    id: 'oil_brush',
    name: 'فرشاة زيتية',
    category: 'فراشي تلوين',
    description: 'فرشاة زيتية سميكة بملامس شعر الفرشاة الطبيعية على القماش',
    size: 22,
    opacity: 0.95,
    flow: 0.9,
    hardness: 0.7,
    spacing: 0.08,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: true,
    angle: 60,
    scatter: 1.5,
  },
  acrylic: {
    id: 'acrylic',
    name: 'فرشاة أكريليك',
    category: 'فراشي تلوين',
    description: 'ألوان أكريليك سريعة الجفاف بتغطية قوية وخطوط واضحة المعالم',
    size: 18,
    opacity: 0.95,
    flow: 0.95,
    hardness: 0.8,
    spacing: 0.06,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  charcoal: {
    id: 'charcoal',
    name: 'فحم',
    category: 'فحم وباستيل',
    description: 'فحم طبيعي غني ذو ملمس حبيبي خشن للتخطيط والتظليل الدرامي',
    size: 24,
    opacity: 0.85,
    flow: 0.75,
    hardness: 0.5,
    spacing: 0.12,
    smoothing: 0.3,
    pressureSize: true,
    pressureOpacity: true,
    angle: 45,
    scatter: 5,
  },
  chalk: {
    id: 'chalk',
    name: 'طباشير',
    category: 'فحم وباستيل',
    description: 'طباشير جاف ببودرة ناعمة وملمس متفتت كلاسيكي',
    size: 20,
    opacity: 0.8,
    flow: 0.7,
    hardness: 0.6,
    spacing: 0.14,
    smoothing: 0.25,
    pressureSize: true,
    pressureOpacity: true,
    angle: 30,
    scatter: 6,
  },
  pastel: {
    id: 'pastel',
    name: 'باستيل',
    category: 'فحم وباستيل',
    description: 'باستيل ناعم مخملي يندمج بسهولة لإنشاء تدرجات لونية ساحرة',
    size: 26,
    opacity: 0.8,
    flow: 0.7,
    hardness: 0.4,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 20,
    scatter: 4,
  },
  crayon: {
    id: 'crayon',
    name: 'ألوان شمعية',
    category: 'فحم وباستيل',
    description: 'ألوان شمع شمعية ذات ملمس غير متجانس يحاكي الرسم اليدوي',
    size: 16,
    opacity: 0.9,
    flow: 0.85,
    hardness: 0.7,
    spacing: 0.12,
    smoothing: 0.2,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 3.5,
  },
  spray: {
    id: 'spray',
    name: 'بخاخ',
    category: 'تأثيرات وبكسل',
    description: 'علبة رذاذ وبخاخ غرافيتي بنقاط متناثرة متباعدة',
    size: 38,
    opacity: 0.7,
    flow: 0.6,
    hardness: 0.1,
    spacing: 0.2,
    smoothing: 0.2,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 18,
  },
  textured: {
    id: 'textured',
    name: 'فرشاة نسيجية',
    category: 'تأثيرات وبكسل',
    description: 'فرشاة بنمط قماش كانفاس متقاطع لإضفاء عمق فني للأعمال',
    size: 30,
    opacity: 0.85,
    flow: 0.8,
    hardness: 0.6,
    spacing: 0.1,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 8,
  },
  glow_light: {
    id: 'glow_light',
    name: 'فرشاة الإضاءة والنور',
    category: 'تأثيرات وبكسل',
    description: 'تضيف توهجاً وإضاءة ناعمة متدرجة تتفاعل مع الألوان وتراكم الضوء',
    size: 55,
    opacity: 0.8,
    flow: 0.65,
    hardness: 0.1,
    spacing: 0.08,
    smoothing: 0.6,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
    glowAmount: 0.85,
    buildUp: 0.75,
    blendMode: 'screen',
  },
  laser: {
    id: 'laser',
    name: 'فرشاة ليزر',
    category: 'تأثيرات وبكسل',
    description: 'إضاءة ليزر تزيد نضارة النور داخل العناصر والبكسلات المرسومة فقط بدون أي انتشار أو Glow خارجي',
    size: 40,
    opacity: 0.9,
    flow: 0.75,
    hardness: 0.15,
    spacing: 0.05,
    smoothing: 0.7,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
    glowAmount: 0.9,
    buildUp: 0.8,
    blendMode: 'lighter',
  },
  smudge: {
    id: 'smudge',
    name: 'فرشاة دمج',
    category: 'تأثيرات وبكسل',
    description: 'أداة دمج سائل تمزج الألوان المرسومة مثل طرف الإصبع',
    size: 25,
    opacity: 0.7,
    flow: 0.7,
    hardness: 0.3,
    spacing: 0.08,
    smoothing: 0.5,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  blur: {
    id: 'blur',
    name: 'فرشاة تمويه',
    category: 'تأثيرات وبكسل',
    description: 'تنعيم وتمويه الحواف الصامتة لإنشاء عمق ميداني هادئ',
    size: 28,
    opacity: 0.65,
    flow: 0.6,
    hardness: 0.2,
    spacing: 0.1,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  pixel: {
    id: 'pixel',
    name: 'فرشاة بكسل',
    category: 'تأثيرات وبكسل',
    description: 'فرشاة رسم البكسل آرت (Pixel Art) بحواف حادة بدون تنعيم نهائياً',
    size: 4,
    opacity: 1.0,
    flow: 1.0,
    hardness: 1.0,
    spacing: 0.01,
    smoothing: 0.0,
    pressureSize: false,
    pressureOpacity: false,
    angle: 0,
    scatter: 0,
  },
  eraser: {
    id: 'eraser',
    name: 'ممحاة ناعمة / صلبة',
    category: 'رصاص وتخطيط',
    description: 'ممحاة لمسح الخطوط والألوان بشفافية أو حدة حسب الإعدادات',
    size: 22,
    opacity: 1.0,
    flow: 1.0,
    hardness: 0.8,
    spacing: 0.08,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0,
  },
  charcoal_eraser: {
    id: 'charcoal_eraser',
    name: '🧽 استيكة الفحم',
    category: 'فحم وباستيل',
    description: 'استيكة فحم عجين لتفتيح وإبراز إضاءات الفحم والجرافيت بملامس حبيبية طبيعية وتدريجية',
    size: 28,
    opacity: 0.5,
    flow: 0.5,
    hardness: 0.4,
    spacing: 0.08,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 3.5,
    texture: 0.65,
  },
  pencil_9h: {
    id: 'pencil_9h',
    name: 'قلم 9H',
    category: '✏️ أقلام الجرافيت',
    description: 'أصلب درجات الرصاص وأكثرها خفة للخطوط والرسوم الهندسية الدقيقة للغاية',
    size: 2,
    opacity: 0.25,
    flow: 0.35,
    hardness: 0.95,
    spacing: 0.05,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.1,
  },
  pencil_8h: {
    id: 'pencil_8h',
    name: 'قلم 8H',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم رصاص صلب جداً وخفيف للغاية للخطوط الأولية فائقة الدقة',
    size: 2,
    opacity: 0.3,
    flow: 0.4,
    hardness: 0.92,
    spacing: 0.05,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.15,
  },
  pencil_7h: {
    id: 'pencil_7h',
    name: 'قلم 7H',
    category: '✏️ أقلام الجرافيت',
    description: 'رصاص صلب وخفيف جداً، مثالي للمخططات والتفاصيل الهندسية والخرائط',
    size: 2,
    opacity: 0.35,
    flow: 0.45,
    hardness: 0.9,
    spacing: 0.05,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.2,
  },
  pencil_6h: {
    id: 'pencil_6h',
    name: 'قلم 6H',
    category: '✏️ أقلام الجرافيت',
    description: 'رصاص صلب ذو خط رفيع ودقيق، مناسب للطبقات التأسيسية الفاتحة',
    size: 2,
    opacity: 0.4,
    flow: 0.5,
    hardness: 0.88,
    spacing: 0.05,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.25,
  },
  pencil_5h: {
    id: 'pencil_5h',
    name: 'قلم 5H',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم رصاص تأسيسي خفيف وصلب لتهيئة أبعاد الرسم المبدئي',
    size: 2,
    opacity: 0.45,
    flow: 0.55,
    hardness: 0.85,
    spacing: 0.06,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.3,
  },
  pencil_4h: {
    id: 'pencil_4h',
    name: 'قلم 4H',
    category: '✏️ أقلام الجرافيت',
    description: 'خط متماسك وخفيف لرسم الخطوط الفنية دون إحداث بقع داكنة',
    size: 2,
    opacity: 0.5,
    flow: 0.6,
    hardness: 0.82,
    spacing: 0.06,
    smoothing: 0.4,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.35,
  },
  pencil_3h: {
    id: 'pencil_3h',
    name: 'قلم 3H',
    category: '✏️ أقلام الجرافيت',
    description: 'رصاص خفيف للمستويات الأولى من تظليل الأجسام المضيئة وتحديد الأبعاد',
    size: 3,
    opacity: 0.55,
    flow: 0.65,
    hardness: 0.8,
    spacing: 0.06,
    smoothing: 0.38,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.4,
  },
  pencil_2h: {
    id: 'pencil_2h',
    name: 'قلم 2H',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم رصاص صلب كلاسيكي للخطوط الفاتحة والتفاصيل الدقيقة والـSketch التمهيدي',
    size: 3,
    opacity: 0.6,
    flow: 0.7,
    hardness: 0.78,
    spacing: 0.07,
    smoothing: 0.38,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.45,
  },
  pencil_h: {
    id: 'pencil_h',
    name: 'قلم H',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم رصاص صلب بدرجة خفيفة، ممتاز للبناء والخطوط التأسيسية الهادئة',
    size: 3,
    opacity: 0.65,
    flow: 0.75,
    hardness: 0.75,
    spacing: 0.07,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.5,
  },
  pencil_f: {
    id: 'pencil_f',
    name: 'قلم F',
    category: '✏️ أقلام الجرافيت',
    description: 'درجة متوسطة حادة السن متزنة الكثافة للخطوط النظيفة واللمسات الفنية الدقيقة',
    size: 3,
    opacity: 0.7,
    flow: 0.78,
    hardness: 0.7,
    spacing: 0.07,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.6,
  },
  pencil_hb_grad: {
    id: 'pencil_hb_grad',
    name: 'قلم HB',
    category: '✏️ أقلام الجرافيت',
    description: 'الدرجة الكلاسيكية العالمية الأكثر توازناً للرسم والتخطيط والكتابة السلسة',
    size: 4,
    opacity: 0.75,
    flow: 0.8,
    hardness: 0.65,
    spacing: 0.08,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 0.8,
  },
  pencil_b: {
    id: 'pencil_b',
    name: 'قلم B',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم رصاص ناعم يبدأ فيه وضوح سواد الجرافيت للتظليل الخفيف والناعم',
    size: 4,
    opacity: 0.8,
    flow: 0.82,
    hardness: 0.6,
    spacing: 0.08,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.0,
  },
  pencil_2b: {
    id: 'pencil_2b',
    name: 'قلم 2B',
    category: '✏️ أقلام الجرافيت',
    description: 'الدرجة المفضلة للفنانين لتظليل الظلال المتوسطة وتفاصيل الوجوه بدقة وسلاسة',
    size: 5,
    opacity: 0.83,
    flow: 0.84,
    hardness: 0.55,
    spacing: 0.09,
    smoothing: 0.35,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.2,
  },
  pencil_3b: {
    id: 'pencil_3b',
    name: 'قلم 3B',
    category: '✏️ أقلام الجرافيت',
    description: 'ناعم وداكن، يعطي تدرجات غنية بالرصاص المنساب وسهل الدمج',
    size: 5,
    opacity: 0.86,
    flow: 0.86,
    hardness: 0.5,
    spacing: 0.09,
    smoothing: 0.32,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.5,
  },
  pencil_4b: {
    id: 'pencil_4b',
    name: 'قلم 4B',
    category: '✏️ أقلام الجرافيت',
    description: 'رصاص داكن ناعم جداً للتظليل العميق وإبراز مستويات التباين القوية',
    size: 6,
    opacity: 0.89,
    flow: 0.88,
    hardness: 0.45,
    spacing: 0.1,
    smoothing: 0.32,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 1.8,
  },
  pencil_5b: {
    id: 'pencil_5b',
    name: 'قلم 5B',
    category: '✏️ أقلام الجرافيت',
    description: 'قلم غني بمسحوق الجرافيت الناعم للتظليل الواسع والظلال المعتمة',
    size: 6,
    opacity: 0.92,
    flow: 0.9,
    hardness: 0.4,
    spacing: 0.1,
    smoothing: 0.3,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 2.2,
  },
  pencil_6b: {
    id: 'pencil_6b',
    name: 'قلم 6B',
    category: '✏️ أقلام الجرافيت',
    description: 'ناعم للغاية وداكن جداً يعزز إبراز تفاصيل العتمة وتدرجات الظلال الكثيفة',
    size: 7,
    opacity: 0.94,
    flow: 0.92,
    hardness: 0.35,
    spacing: 0.11,
    smoothing: 0.3,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 2.6,
  },
  pencil_7b: {
    id: 'pencil_7b',
    name: 'قلم 7B',
    category: '✏️ أقلام الجرافيت',
    description: 'رصاص جرافيت فحمى فائق السواد والنعومة للتظليل المساحي الغامق جداً',
    size: 7,
    opacity: 0.96,
    flow: 0.94,
    hardness: 0.3,
    spacing: 0.11,
    smoothing: 0.28,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 3.0,
  },
  pencil_8b: {
    id: 'pencil_8b',
    name: 'قلم 8B',
    category: '✏️ أقلام الجرافيت',
    description: 'سواد كثيف جداً وملمس ناعم غني لتغطية سريعة ومثيرة للاهتمام للظل المعتم',
    size: 8,
    opacity: 0.98,
    flow: 0.96,
    hardness: 0.25,
    spacing: 0.12,
    smoothing: 0.28,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 3.4,
  },
  pencil_9b: {
    id: 'pencil_9b',
    name: 'قلم 9B',
    category: '✏️ أقلام الجرافيت',
    description: 'أقصى درجات السواد والنعومة للجرافيت، سواد فاحم وناعم يشبه الفحم للتظليل العميق',
    size: 8,
    opacity: 1.0,
    flow: 0.98,
    hardness: 0.2,
    spacing: 0.12,
    smoothing: 0.25,
    pressureSize: true,
    pressureOpacity: true,
    angle: 0,
    scatter: 4.0,
  },
};

export const PRESET_COLOR_PALETTES: ColorPalette[] = [
  {
    id: 'essential',
    name: 'الألوان الأساسية',
    colors: [
      '#000000', '#ffffff', '#e63946', '#f1faee', '#a8dadc', '#457b9d', '#1d3557',
      '#f77f00', '#fcbf49', '#eae2b7', '#2a9d8f', '#264653', '#e76f51', '#9b5de5'
    ]
  },
  {
    id: 'nature',
    name: 'ألوان الطبيعة',
    colors: [
      '#2d6a4f', '#40916c', '#52b788', '#74c69d', '#95d5b2', '#b7e4c7', '#d8f3dc',
      '#606c38', '#283618', '#dda15e', '#bc6c25', '#8c1c13', '#bf4342', '#e7c169'
    ]
  },
  {
    id: 'skin_tones',
    name: 'درجات البشرة',
    colors: [
      '#2d1b00', '#4a2c00', '#6f441b', '#8d5524', '#c68642', '#e0ac69', '#f1c27d',
      '#ffdbac', '#fae1c5', '#fce8d5', '#e8b4b8', '#d48b94', '#9e5a63', '#4a252b'
    ]
  },
  {
    id: 'pastel',
    name: 'ألوان الباستيل',
    colors: [
      '#ffb3ba', '#ffdfba', '#ffffba', '#baffc9', '#bae1ff', '#e8dff5', '#fce1e4',
      '#fcf4dd', '#ddedea', '#daeaf6', '#fedcd2', '#dfccf1', '#f6eac2', '#c1e7e3'
    ]
  },
  {
    id: 'grayscale',
    name: 'تدرجات الرمادي',
    colors: [
      '#000000', '#171717', '#262626', '#404040', '#525252', '#737373', '#a3a3a3',
      '#d4d4d4', '#e5e5e5', '#f5f5f5', '#fafafa', '#ffffff', '#334155', '#64748b'
    ]
  },
  {
    id: 'cyberpunk_neon',
    name: 'ألوان النيون',
    colors: [
      '#00f0ff', '#ff003c', '#ffe600', '#05d9e8', '#ff2a6d', '#01012b', '#d1f7ff',
      '#00ff66', '#ff00ff', '#7928ca', '#39ff14', '#ff073a', '#00e5ff', '#ffb800'
    ]
  }
];
